name: AppScan SAST Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  appscan-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AppScan SAST
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          application_id: ${{ secrets.ASOC_APP_ID }}
          scan_name: "GitHub Actions SAST Scan"
          personal_scan: false
          static_analysis_only: false
          open_source_only: false
          scan_build_outputs: false
          wait_for_analysis: true
          analysis_timeout_minutes: 30
          fail_for_noncompliance: true
          failure_threshold: 5
