name: Deploy with Security Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run AppScan SAST
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          application_name: 'Testing AppScan'
          scan_name: 'Deploy Scan'
          scan_type: 'SAST'
          fail_on_findings: true

      - name: Deploy Application
        run: |
          # Your deployment commands here
        if: success()
